### ISSUE TITLE
Error running 

### ISSUE THREAD

**Issue by mcintosh101** [axemclion/perfjankie#31]
When I run from the command line `browser-perf --verbose --config-file=local.config.json` I get this error:

```
bp:index Selenium is on localhost +0ms
  bp:metrics Initializing Metrics +2ms
  bp:probes Registering probe +66ms PerfLogProbe
  bp:probes:AndroidTracingProbe Initialize +1ms
  bp:probes Registering probe +0ms AndroidTracingProbe
  bp:probes Registering probe +2ms PerfLogProbe
  bp:probes Registering probe +0ms AndroidTracingProbe
  bp:probes Registering probe +1ms RafBenchmarkingProbe
  bp:probes Registering probe +2ms NavTimingProbe
  bp:probes Registering probe +1ms NetworkResourcesProbe
  bp:metrics TimelineMetrics +2ms setup called
  bp:metrics ChromeTracingMetrics +0ms setup called
  bp:metrics NetworkResources +0ms setup called
  bp:probes setup +1ms
  bp:probes PerfLogProbe +0ms setup called
  bp:probes AndroidTracingProbe +0ms setup called
  bp:probes NetworkResourcesProbe +0ms setup called
  bp:index Stating browser with +1ms {"browserName":"android","platform":"OS X","chromeOptions":{"androidActivity":"com.ionicframework.clientapp176148.MainActivity","androidPackage":"com.ionicframework.clientapp176148","perfLoggingPrefs":{"traceCategories":",blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame"},"args":["--enable-gpu-benchmarking","--enable-thread-composting"]},"loggingPrefs":{"performance":"ALL"}}
  bp:selenium CALL +0ms init({"browserName":"android","platform":"OS X","chromeOptions":{"andr
  bp:selenium CALL +19ms quit()
[ { [Error: [init({"browserName":"android","platform":"OS X","chromeOptions":{"androidActivity":"com.ionicframework.clientapp176148.MainActivity","androidPackage":"com.ionicframework.clientapp176148","perfLoggingPrefs":{"traceCategories":",blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame"},"args":["--enable-gpu-benchmarking","--enable-thread-composting"]},"loggingPrefs":{"performance":"ALL"}})] The environment you requested was unavailable.] data: 'unknown command: wd/hub/session' } ]
Error: [init({"browserName":"android","platform":"OS X","chromeOptions":{"androidActivity":"com.ionicframework.clientapp176148.MainActivity","androidPackage":"com.ionicframework.clientapp176148","perfLoggingPrefs":{"traceCategories":",blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame"},"args":["--enable-gpu-benchmarking","--enable-thread-composting"]},"loggingPrefs":{"performance":"ALL"}})] The environment you requested was unavailable.
    at /usr/local/lib/node_modules/browser-perf/node_modules/wd/lib/webdriver.js:129:15
    at Request._callback (/usr/local/lib/node_modules/browser-perf/node_modules/wd/lib/http-utils.js:87:7)
    at Request.self.callback (/usr/local/lib/node_modules/browser-perf/node_modules/wd/node_modules/request/request.js:368:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/browser-perf/node_modules/wd/node_modules/request/request.js:1219:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/browser-perf/node_modules/wd/node_modules/request/request.js:1167:12)
    at emitNone (events.js:85:20)
```

And when I run `perfjankie --config-file=local.config.json` I get this error:

```
Starting PerfJankie
Trying to see if the database exists
Starting Browser Perf
[ { [Error: [init({"browserName":"android","platform":"OS X","chromeOptions":{"androidActivity":"com.ionicframework.clientapp176148.MainActivity","androidPackage":"com.ionicframework.clientapp176148","perfLoggingPrefs":{"traceCategories":",blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame"},"args":["--enable-gpu-benchmarking","--enable-thread-composting"]},"loggingPrefs":{"performance":"ALL"}})] The environment you requested was unavailable.] data: 'unknown command: wd/hub/session' } ]
[ { [Error: [init({"browserName":"android","platform":"OS X","chromeOptions":{"androidActivity":"com.ionicframework.clientapp176148.MainActivity","androidPackage":"com.ionicframework.clientapp176148","perfLoggingPrefs":{"traceCategories":",blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame"},"args":["--enable-gpu-benchmarking","--enable-thread-composting"]},"loggingPrefs":{"performance":"ALL"}})] The environment you requested was unavailable.] data: 'unknown command: wd/hub/session' } ] null
```

Here is my `local.config.json` file contents:

``` json
{
    "url": "http://localhost:8100/",
    "name": "Performance Testing",
    "repeat": 3,
    "browsers": [{
        "browserName": "android",
        "platform": "OS X",
        "chromeOptions": {
            "androidActivity": "com.ionicframework.XYZ.MainActivity",
            "androidPackage": "com.ionicframework.XYZ"
        }
    }],
    "selenium": {
        "hostname": "localhost",
        "port": 9515
    },
    "couch": {
        "server": "http://localhost:5984",
        "username": "XXXXX",
        "pwd": "YYYYY",
        "database": "ZZZZZ"
    }
}
```

Is anyone else getting issues like this? Or does someone possibly know what I have set up wrong?

Thanks!
Alex.

**Comment by Darkoon** [comment]
Got the same issue trying to test my Cordova app with local.config.json: 
```
{
	"browsers":  [{
		"browserName": "cordova",
		"chromeOptions": {
			"androidActivity": "com.coolappz.AECordova2.MainActivity",
			"androidPackage": "com.coolappz.AECordova2"
		}
	}],
	"selenium": {
		"hostname": "localhost",
		"port": 4444
	},

	"couch": {
		"server": "http://localhost:5984",
		"database": "perfjankie-test"
	}
}
```
Selenium server is up and running, couchDB is working fine. Any tips how to do tests for cordova apps?

**Comment by axemclion** [comment]
@Darkoon Are you still having this error ? What error do you see ?

**Comment by axemclion** [comment]
Are you still having this issue ? Closing this issue since there has been no action on it. If you still have the issue, please reopen it and I will be glad to help.
